public class ProfileFullAddress {
    public String type {get; set;}
    public String line1 {get; set;}
    public String line2 {get; set;}
    public String line3 {get; set;}
    public String line4 {get; set;}
    public String city {get; set;}
    public string stateProvince {get; set;}
    public String postalCode {get; set;}
    public String country {get; set;}
    public String isPrimary {get; set;}
}